// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCollection.web.Data;

#nullable disable

namespace MyCollection.web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyCollection.web.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Gerrit",
                            LastName = "Baeten"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "",
                            LastName = "Banksy"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Etienne",
                            LastName = "Bauwens"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Geert",
                            LastName = "Bauwens"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "René",
                            LastName = "Bekaert"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
